version: 0.0
os: linux
files:
  - source: ./refapp.war
    destination: /var/lib/tomcat/webapps
hooks:
  BeforeInstall:
    #- location: scripts/install_dependencies.sh
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    #- location: scripts/change_permissions.sh
    - location: change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    #- location: scripts/start_server.sh
    - location: start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    #- location: scripts/stop_server.sh
    - location: stop_server.sh
      timeout: 300
      runas: root
