version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - apt-get install maven -y
  build:
    commands:
      - mvn install war:war
artifacts:
  files:
    - target/refapp.war
    - appspec.yml
